/**
  * \file VecIdecVDpch.cpp
  * vector VecIdecVDpch (implementation)
  * \author Alexander Wirthmueller
  * \date created: 30 Dec 2017
  * \date modified: 30 Dec 2017
  */

#include "VecIdecVDpch.h"

/******************************************************************************
 namespace VecIdecVDpch
 ******************************************************************************/

uint VecIdecVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchappdlgidecfilextrmeddata") return DPCHAPPDLGIDECFILEXTRMEDDATA;
	else if (s == "dpchappdlgidecfilextrmeddo") return DPCHAPPDLGIDECFILEXTRMEDDO;
	else if (s == "dpchappdlgidecmisnewdata") return DPCHAPPDLGIDECMISNEWDATA;
	else if (s == "dpchappdlgidecmisnewdo") return DPCHAPPDLGIDECMISNEWDO;
	else if (s == "dpchappdlgidecnavloainidata") return DPCHAPPDLGIDECNAVLOAINIDATA;
	else if (s == "dpchappdlgidecnavloainido") return DPCHAPPDLGIDECNAVLOAINIDO;
	else if (s == "dpchappdlgidectounewdata") return DPCHAPPDLGIDECTOUNEWDATA;
	else if (s == "dpchappdlgidectounewdo") return DPCHAPPDLGIDECTOUNEWDO;
	else if (s == "dpchappdlgidecutlfusiondata") return DPCHAPPDLGIDECUTLFUSIONDATA;
	else if (s == "dpchappdlgidecutlfusiondo") return DPCHAPPDLGIDECUTLFUSIONDO;
	else if (s == "dpchappdlgidecutlphidata") return DPCHAPPDLGIDECUTLPHIDATA;
	else if (s == "dpchappdlgidecutlphido") return DPCHAPPDLGIDECUTLPHIDO;
	else if (s == "dpchappdlgidecutlqcdalndata") return DPCHAPPDLGIDECUTLQCDALNDATA;
	else if (s == "dpchappdlgidecutlqcdalndo") return DPCHAPPDLGIDECUTLQCDALNDO;
	else if (s == "dpchappdlgidecutlqcdnucdata") return DPCHAPPDLGIDECUTLQCDNUCDATA;
	else if (s == "dpchappdlgidecutlqcdnucdo") return DPCHAPPDLGIDECUTLQCDNUCDO;
	else if (s == "dpchappdlgidecutlstereodata") return DPCHAPPDLGIDECUTLSTEREODATA;
	else if (s == "dpchappdlgidecutlstereodo") return DPCHAPPDLGIDECUTLSTEREODO;
	else if (s == "dpchappdlgidecutlthetadata") return DPCHAPPDLGIDECUTLTHETADATA;
	else if (s == "dpchappdlgidecutlthetado") return DPCHAPPDLGIDECUTLTHETADO;
	else if (s == "dpchappidecad1controldata") return DPCHAPPIDECAD1CONTROLDATA;
	else if (s == "dpchappidecad1controldo") return DPCHAPPIDECAD1CONTROLDO;
	else if (s == "dpchappidecad1do") return DPCHAPPIDECAD1DO;
	else if (s == "dpchappidecalert") return DPCHAPPIDECALERT;
	else if (s == "dpchappidecfildetaildata") return DPCHAPPIDECFILDETAILDATA;
	else if (s == "dpchappidecfildetaildo") return DPCHAPPIDECFILDETAILDO;
	else if (s == "dpchappidecfildo") return DPCHAPPIDECFILDO;
	else if (s == "dpchappidecfillistdata") return DPCHAPPIDECFILLISTDATA;
	else if (s == "dpchappidecfillistdo") return DPCHAPPIDECFILLISTDO;
	else if (s == "dpchappidecfilrecdo") return DPCHAPPIDECFILRECDO;
	else if (s == "dpchappideciaqdo") return DPCHAPPIDECIAQDO;
	else if (s == "dpchappideciaqlivedata") return DPCHAPPIDECIAQLIVEDATA;
	else if (s == "dpchappideciaqlivedo") return DPCHAPPIDECIAQLIVEDO;
	else if (s == "dpchappideciaqmechdata") return DPCHAPPIDECIAQMECHDATA;
	else if (s == "dpchappideciaqmechdo") return DPCHAPPIDECIAQMECHDO;
	else if (s == "dpchappideciaqqcdspdata") return DPCHAPPIDECIAQQCDSPDATA;
	else if (s == "dpchappideciaqqcdspdo") return DPCHAPPIDECIAQQCDSPDO;
	else if (s == "dpchappideciaqscilldata") return DPCHAPPIDECIAQSCILLDATA;
	else if (s == "dpchappideciaqscilldo") return DPCHAPPIDECIAQSCILLDO;
	else if (s == "dpchappidecinit") return DPCHAPPIDECINIT;
	else if (s == "dpchappidecmis1ntourdata") return DPCHAPPIDECMIS1NTOURDATA;
	else if (s == "dpchappidecmis1ntourdo") return DPCHAPPIDECMIS1NTOURDO;
	else if (s == "dpchappidecmisdetaildata") return DPCHAPPIDECMISDETAILDATA;
	else if (s == "dpchappidecmisdetaildo") return DPCHAPPIDECMISDETAILDO;
	else if (s == "dpchappidecmisdo") return DPCHAPPIDECMISDO;
	else if (s == "dpchappidecmislistdata") return DPCHAPPIDECMISLISTDATA;
	else if (s == "dpchappidecmislistdo") return DPCHAPPIDECMISLISTDO;
	else if (s == "dpchappidecmisrecdo") return DPCHAPPIDECMISRECDO;
	else if (s == "dpchappidecmisref1nfiledata") return DPCHAPPIDECMISREF1NFILEDATA;
	else if (s == "dpchappidecmisref1nfiledo") return DPCHAPPIDECMISREF1NFILEDO;
	else if (s == "dpchappidecnavdo") return DPCHAPPIDECNAVDO;
	else if (s == "dpchappidecnavmaintdata") return DPCHAPPIDECNAVMAINTDATA;
	else if (s == "dpchappidecnavmaintdo") return DPCHAPPIDECNAVMAINTDO;
	else if (s == "dpchappidecnavoprdata") return DPCHAPPIDECNAVOPRDATA;
	else if (s == "dpchappidecnavoprdo") return DPCHAPPIDECNAVOPRDO;
	else if (s == "dpchappidecnavpredo") return DPCHAPPIDECNAVPREDO;
	else if (s == "dpchappidecresume") return DPCHAPPIDECRESUME;
	else if (s == "dpchappidecscfconndata") return DPCHAPPIDECSCFCONNDATA;
	else if (s == "dpchappidecscfconndo") return DPCHAPPIDECSCFCONNDO;
	else if (s == "dpchappidecscfdo") return DPCHAPPIDECSCFDO;
	else if (s == "dpchappidecscflwirdata") return DPCHAPPIDECSCFLWIRDATA;
	else if (s == "dpchappidecscflwirdo") return DPCHAPPIDECSCFLWIRDO;
	else if (s == "dpchappidecscfmechdata") return DPCHAPPIDECSCFMECHDATA;
	else if (s == "dpchappidecscfmechdo") return DPCHAPPIDECSCFMECHDO;
	else if (s == "dpchappidecscfopticsdata") return DPCHAPPIDECSCFOPTICSDATA;
	else if (s == "dpchappidecscfopticsdo") return DPCHAPPIDECSCFOPTICSDO;
	else if (s == "dpchappidecscfqcddata") return DPCHAPPIDECSCFQCDDATA;
	else if (s == "dpchappidecscfqcddo") return DPCHAPPIDECSCFQCDDO;
	else if (s == "dpchappidecscfrecorddata") return DPCHAPPIDECSCFRECORDDATA;
	else if (s == "dpchappidecscfrecorddo") return DPCHAPPIDECSCFRECORDDO;
	else if (s == "dpchappidecscfstatusdo") return DPCHAPPIDECSCFSTATUSDO;
	else if (s == "dpchappidecscftriggerdata") return DPCHAPPIDECSCFTRIGGERDATA;
	else if (s == "dpchappidecscftriggerdo") return DPCHAPPIDECSCFTRIGGERDO;
	else if (s == "dpchappidectoudetaildata") return DPCHAPPIDECTOUDETAILDATA;
	else if (s == "dpchappidectoudetaildo") return DPCHAPPIDECTOUDETAILDO;
	else if (s == "dpchappidectoudo") return DPCHAPPIDECTOUDO;
	else if (s == "dpchappidectoulistdata") return DPCHAPPIDECTOULISTDATA;
	else if (s == "dpchappidectoulistdo") return DPCHAPPIDECTOULISTDO;
	else if (s == "dpchappidectourecdo") return DPCHAPPIDECTOURECDO;
	else if (s == "dpchappidectouref1nfiledata") return DPCHAPPIDECTOUREF1NFILEDATA;
	else if (s == "dpchappidectouref1nfiledo") return DPCHAPPIDECTOUREF1NFILEDO;
	else if (s == "dpchappidecusgaaccessdata") return DPCHAPPIDECUSGAACCESSDATA;
	else if (s == "dpchappidecusgaaccessdo") return DPCHAPPIDECUSGAACCESSDO;
	else if (s == "dpchappidecusgdetaildata") return DPCHAPPIDECUSGDETAILDATA;
	else if (s == "dpchappidecusgdetaildo") return DPCHAPPIDECUSGDETAILDO;
	else if (s == "dpchappidecusgdo") return DPCHAPPIDECUSGDO;
	else if (s == "dpchappidecusglistdata") return DPCHAPPIDECUSGLISTDATA;
	else if (s == "dpchappidecusglistdo") return DPCHAPPIDECUSGLISTDO;
	else if (s == "dpchappidecusgmnuserdata") return DPCHAPPIDECUSGMNUSERDATA;
	else if (s == "dpchappidecusgmnuserdo") return DPCHAPPIDECUSGMNUSERDO;
	else if (s == "dpchappidecusgrecdo") return DPCHAPPIDECUSGRECDO;
	else if (s == "dpchappidecusr1nsessiondata") return DPCHAPPIDECUSR1NSESSIONDATA;
	else if (s == "dpchappidecusr1nsessiondo") return DPCHAPPIDECUSR1NSESSIONDO;
	else if (s == "dpchappidecusraaccessdata") return DPCHAPPIDECUSRAACCESSDATA;
	else if (s == "dpchappidecusraaccessdo") return DPCHAPPIDECUSRAACCESSDO;
	else if (s == "dpchappidecusrdetaildata") return DPCHAPPIDECUSRDETAILDATA;
	else if (s == "dpchappidecusrdetaildo") return DPCHAPPIDECUSRDETAILDO;
	else if (s == "dpchappidecusrdo") return DPCHAPPIDECUSRDO;
	else if (s == "dpchappidecusrlistdata") return DPCHAPPIDECUSRLISTDATA;
	else if (s == "dpchappidecusrlistdo") return DPCHAPPIDECUSRLISTDO;
	else if (s == "dpchappidecusrmnusergroupdata") return DPCHAPPIDECUSRMNUSERGROUPDATA;
	else if (s == "dpchappidecusrmnusergroupdo") return DPCHAPPIDECUSRMNUSERGROUPDO;
	else if (s == "dpchappidecusrrecdo") return DPCHAPPIDECUSRRECDO;
	else if (s == "dpchappidecutldo") return DPCHAPPIDECUTLDO;
	else if (s == "dpchappidecutlspitermdata") return DPCHAPPIDECUTLSPITERMDATA;
	else if (s == "dpchappidecutlspitermdo") return DPCHAPPIDECUTLSPITERMDO;
	else if (s == "dpchapprootideclogin") return DPCHAPPROOTIDECLOGIN;
	else if (s == "dpchengdlgidecfilextrmeddata") return DPCHENGDLGIDECFILEXTRMEDDATA;
	else if (s == "dpchengdlgidecmisnewdata") return DPCHENGDLGIDECMISNEWDATA;
	else if (s == "dpchengdlgidecnavloainidata") return DPCHENGDLGIDECNAVLOAINIDATA;
	else if (s == "dpchengdlgidectounewdata") return DPCHENGDLGIDECTOUNEWDATA;
	else if (s == "dpchengdlgidecutlfusiondata") return DPCHENGDLGIDECUTLFUSIONDATA;
	else if (s == "dpchengdlgidecutlphidata") return DPCHENGDLGIDECUTLPHIDATA;
	else if (s == "dpchengdlgidecutlqcdalndata") return DPCHENGDLGIDECUTLQCDALNDATA;
	else if (s == "dpchengdlgidecutlqcdnucdata") return DPCHENGDLGIDECUTLQCDNUCDATA;
	else if (s == "dpchengdlgidecutlstereodata") return DPCHENGDLGIDECUTLSTEREODATA;
	else if (s == "dpchengdlgidecutlthetadata") return DPCHENGDLGIDECUTLTHETADATA;
	else if (s == "dpchengidecack") return DPCHENGIDECACK;
	else if (s == "dpchengidecad1controldata") return DPCHENGIDECAD1CONTROLDATA;
	else if (s == "dpchengidecad1data") return DPCHENGIDECAD1DATA;
	else if (s == "dpchengidecad1headbardata") return DPCHENGIDECAD1HEADBARDATA;
	else if (s == "dpchengidecalert") return DPCHENGIDECALERT;
	else if (s == "dpchengidecconfirm") return DPCHENGIDECCONFIRM;
	else if (s == "dpchengidecfildata") return DPCHENGIDECFILDATA;
	else if (s == "dpchengidecfildetaildata") return DPCHENGIDECFILDETAILDATA;
	else if (s == "dpchengidecfilheadbardata") return DPCHENGIDECFILHEADBARDATA;
	else if (s == "dpchengidecfillistdata") return DPCHENGIDECFILLISTDATA;
	else if (s == "dpchengidecfilrecdata") return DPCHENGIDECFILRECDATA;
	else if (s == "dpchengideciaqdata") return DPCHENGIDECIAQDATA;
	else if (s == "dpchengideciaqheadbardata") return DPCHENGIDECIAQHEADBARDATA;
	else if (s == "dpchengideciaqlivedata") return DPCHENGIDECIAQLIVEDATA;
	else if (s == "dpchengideciaqlivelive") return DPCHENGIDECIAQLIVELIVE;
	else if (s == "dpchengideciaqmechdata") return DPCHENGIDECIAQMECHDATA;
	else if (s == "dpchengideciaqmechlive") return DPCHENGIDECIAQMECHLIVE;
	else if (s == "dpchengideciaqqcdspdata") return DPCHENGIDECIAQQCDSPDATA;
	else if (s == "dpchengideciaqqcdsplive") return DPCHENGIDECIAQQCDSPLIVE;
	else if (s == "dpchengideciaqscilldata") return DPCHENGIDECIAQSCILLDATA;
	else if (s == "dpchengidecmis1ntourdata") return DPCHENGIDECMIS1NTOURDATA;
	else if (s == "dpchengidecmisdata") return DPCHENGIDECMISDATA;
	else if (s == "dpchengidecmisdetaildata") return DPCHENGIDECMISDETAILDATA;
	else if (s == "dpchengidecmisheadbardata") return DPCHENGIDECMISHEADBARDATA;
	else if (s == "dpchengidecmislistdata") return DPCHENGIDECMISLISTDATA;
	else if (s == "dpchengidecmisrecdata") return DPCHENGIDECMISRECDATA;
	else if (s == "dpchengidecmisref1nfiledata") return DPCHENGIDECMISREF1NFILEDATA;
	else if (s == "dpchengidecnavdata") return DPCHENGIDECNAVDATA;
	else if (s == "dpchengidecnavheadbardata") return DPCHENGIDECNAVHEADBARDATA;
	else if (s == "dpchengidecnavmaintdata") return DPCHENGIDECNAVMAINTDATA;
	else if (s == "dpchengidecnavoprdata") return DPCHENGIDECNAVOPRDATA;
	else if (s == "dpchengidecnavpredata") return DPCHENGIDECNAVPREDATA;
	else if (s == "dpchengidecscfconndata") return DPCHENGIDECSCFCONNDATA;
	else if (s == "dpchengidecscfconnlive") return DPCHENGIDECSCFCONNLIVE;
	else if (s == "dpchengidecscfdata") return DPCHENGIDECSCFDATA;
	else if (s == "dpchengidecscfheadbardata") return DPCHENGIDECSCFHEADBARDATA;
	else if (s == "dpchengidecscflwirdata") return DPCHENGIDECSCFLWIRDATA;
	else if (s == "dpchengidecscfmechdata") return DPCHENGIDECSCFMECHDATA;
	else if (s == "dpchengidecscfmechlive") return DPCHENGIDECSCFMECHLIVE;
	else if (s == "dpchengidecscfopticsdata") return DPCHENGIDECSCFOPTICSDATA;
	else if (s == "dpchengidecscfqcddata") return DPCHENGIDECSCFQCDDATA;
	else if (s == "dpchengidecscfrecorddata") return DPCHENGIDECSCFRECORDDATA;
	else if (s == "dpchengidecscfstatusdata") return DPCHENGIDECSCFSTATUSDATA;
	else if (s == "dpchengidecscftriggerdata") return DPCHENGIDECSCFTRIGGERDATA;
	else if (s == "dpchengidecsuspend") return DPCHENGIDECSUSPEND;
	else if (s == "dpchengidectoudata") return DPCHENGIDECTOUDATA;
	else if (s == "dpchengidectoudetaildata") return DPCHENGIDECTOUDETAILDATA;
	else if (s == "dpchengidectouheadbardata") return DPCHENGIDECTOUHEADBARDATA;
	else if (s == "dpchengidectoulistdata") return DPCHENGIDECTOULISTDATA;
	else if (s == "dpchengidectourecdata") return DPCHENGIDECTOURECDATA;
	else if (s == "dpchengidectouref1nfiledata") return DPCHENGIDECTOUREF1NFILEDATA;
	else if (s == "dpchengidecusgaaccessdata") return DPCHENGIDECUSGAACCESSDATA;
	else if (s == "dpchengidecusgdata") return DPCHENGIDECUSGDATA;
	else if (s == "dpchengidecusgdetaildata") return DPCHENGIDECUSGDETAILDATA;
	else if (s == "dpchengidecusgheadbardata") return DPCHENGIDECUSGHEADBARDATA;
	else if (s == "dpchengidecusglistdata") return DPCHENGIDECUSGLISTDATA;
	else if (s == "dpchengidecusgmnuserdata") return DPCHENGIDECUSGMNUSERDATA;
	else if (s == "dpchengidecusgrecdata") return DPCHENGIDECUSGRECDATA;
	else if (s == "dpchengidecusr1nsessiondata") return DPCHENGIDECUSR1NSESSIONDATA;
	else if (s == "dpchengidecusraaccessdata") return DPCHENGIDECUSRAACCESSDATA;
	else if (s == "dpchengidecusrdata") return DPCHENGIDECUSRDATA;
	else if (s == "dpchengidecusrdetaildata") return DPCHENGIDECUSRDETAILDATA;
	else if (s == "dpchengidecusrheadbardata") return DPCHENGIDECUSRHEADBARDATA;
	else if (s == "dpchengidecusrlistdata") return DPCHENGIDECUSRLISTDATA;
	else if (s == "dpchengidecusrmnusergroupdata") return DPCHENGIDECUSRMNUSERGROUPDATA;
	else if (s == "dpchengidecusrrecdata") return DPCHENGIDECUSRRECDATA;
	else if (s == "dpchengidecutldata") return DPCHENGIDECUTLDATA;
	else if (s == "dpchengidecutlheadbardata") return DPCHENGIDECUTLHEADBARDATA;
	else if (s == "dpchengidecutlspitermdata") return DPCHENGIDECUTLSPITERMDATA;
	else if (s == "dpchengidecutlspitermlive") return DPCHENGIDECUTLSPITERMLIVE;
	else if (s == "dpchengsessidecdata") return DPCHENGSESSIDECDATA;
	else if (s == "dpchidecdack") return DPCHIDECDACK;
	else if (s == "dpchidecdquit") return DPCHIDECDQUIT;
	else if (s == "dpchidecdreg") return DPCHIDECDREG;
	else if (s == "dpchidecopdreg") return DPCHIDECOPDREG;
	else if (s == "dpchidecopdunreg") return DPCHIDECOPDUNREG;
	else if (s == "dpchinvidec") return DPCHINVIDEC;
	else if (s == "dpchretidec") return DPCHRETIDEC;

	return(0);
};

string VecIdecVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHAPPDLGIDECFILEXTRMEDDATA) return("DpchAppDlgIdecFilExtrmedData");
	else if (ix == DPCHAPPDLGIDECFILEXTRMEDDO) return("DpchAppDlgIdecFilExtrmedDo");
	else if (ix == DPCHAPPDLGIDECMISNEWDATA) return("DpchAppDlgIdecMisNewData");
	else if (ix == DPCHAPPDLGIDECMISNEWDO) return("DpchAppDlgIdecMisNewDo");
	else if (ix == DPCHAPPDLGIDECNAVLOAINIDATA) return("DpchAppDlgIdecNavLoainiData");
	else if (ix == DPCHAPPDLGIDECNAVLOAINIDO) return("DpchAppDlgIdecNavLoainiDo");
	else if (ix == DPCHAPPDLGIDECTOUNEWDATA) return("DpchAppDlgIdecTouNewData");
	else if (ix == DPCHAPPDLGIDECTOUNEWDO) return("DpchAppDlgIdecTouNewDo");
	else if (ix == DPCHAPPDLGIDECUTLFUSIONDATA) return("DpchAppDlgIdecUtlFusionData");
	else if (ix == DPCHAPPDLGIDECUTLFUSIONDO) return("DpchAppDlgIdecUtlFusionDo");
	else if (ix == DPCHAPPDLGIDECUTLPHIDATA) return("DpchAppDlgIdecUtlPhiData");
	else if (ix == DPCHAPPDLGIDECUTLPHIDO) return("DpchAppDlgIdecUtlPhiDo");
	else if (ix == DPCHAPPDLGIDECUTLQCDALNDATA) return("DpchAppDlgIdecUtlQcdalnData");
	else if (ix == DPCHAPPDLGIDECUTLQCDALNDO) return("DpchAppDlgIdecUtlQcdalnDo");
	else if (ix == DPCHAPPDLGIDECUTLQCDNUCDATA) return("DpchAppDlgIdecUtlQcdnucData");
	else if (ix == DPCHAPPDLGIDECUTLQCDNUCDO) return("DpchAppDlgIdecUtlQcdnucDo");
	else if (ix == DPCHAPPDLGIDECUTLSTEREODATA) return("DpchAppDlgIdecUtlStereoData");
	else if (ix == DPCHAPPDLGIDECUTLSTEREODO) return("DpchAppDlgIdecUtlStereoDo");
	else if (ix == DPCHAPPDLGIDECUTLTHETADATA) return("DpchAppDlgIdecUtlThetaData");
	else if (ix == DPCHAPPDLGIDECUTLTHETADO) return("DpchAppDlgIdecUtlThetaDo");
	else if (ix == DPCHAPPIDECAD1CONTROLDATA) return("DpchAppIdecAd1ControlData");
	else if (ix == DPCHAPPIDECAD1CONTROLDO) return("DpchAppIdecAd1ControlDo");
	else if (ix == DPCHAPPIDECAD1DO) return("DpchAppIdecAd1Do");
	else if (ix == DPCHAPPIDECALERT) return("DpchAppIdecAlert");
	else if (ix == DPCHAPPIDECFILDETAILDATA) return("DpchAppIdecFilDetailData");
	else if (ix == DPCHAPPIDECFILDETAILDO) return("DpchAppIdecFilDetailDo");
	else if (ix == DPCHAPPIDECFILDO) return("DpchAppIdecFilDo");
	else if (ix == DPCHAPPIDECFILLISTDATA) return("DpchAppIdecFilListData");
	else if (ix == DPCHAPPIDECFILLISTDO) return("DpchAppIdecFilListDo");
	else if (ix == DPCHAPPIDECFILRECDO) return("DpchAppIdecFilRecDo");
	else if (ix == DPCHAPPIDECIAQDO) return("DpchAppIdecIaqDo");
	else if (ix == DPCHAPPIDECIAQLIVEDATA) return("DpchAppIdecIaqLiveData");
	else if (ix == DPCHAPPIDECIAQLIVEDO) return("DpchAppIdecIaqLiveDo");
	else if (ix == DPCHAPPIDECIAQMECHDATA) return("DpchAppIdecIaqMechData");
	else if (ix == DPCHAPPIDECIAQMECHDO) return("DpchAppIdecIaqMechDo");
	else if (ix == DPCHAPPIDECIAQQCDSPDATA) return("DpchAppIdecIaqQcdspData");
	else if (ix == DPCHAPPIDECIAQQCDSPDO) return("DpchAppIdecIaqQcdspDo");
	else if (ix == DPCHAPPIDECIAQSCILLDATA) return("DpchAppIdecIaqScillData");
	else if (ix == DPCHAPPIDECIAQSCILLDO) return("DpchAppIdecIaqScillDo");
	else if (ix == DPCHAPPIDECINIT) return("DpchAppIdecInit");
	else if (ix == DPCHAPPIDECMIS1NTOURDATA) return("DpchAppIdecMis1NTourData");
	else if (ix == DPCHAPPIDECMIS1NTOURDO) return("DpchAppIdecMis1NTourDo");
	else if (ix == DPCHAPPIDECMISDETAILDATA) return("DpchAppIdecMisDetailData");
	else if (ix == DPCHAPPIDECMISDETAILDO) return("DpchAppIdecMisDetailDo");
	else if (ix == DPCHAPPIDECMISDO) return("DpchAppIdecMisDo");
	else if (ix == DPCHAPPIDECMISLISTDATA) return("DpchAppIdecMisListData");
	else if (ix == DPCHAPPIDECMISLISTDO) return("DpchAppIdecMisListDo");
	else if (ix == DPCHAPPIDECMISRECDO) return("DpchAppIdecMisRecDo");
	else if (ix == DPCHAPPIDECMISREF1NFILEDATA) return("DpchAppIdecMisRef1NFileData");
	else if (ix == DPCHAPPIDECMISREF1NFILEDO) return("DpchAppIdecMisRef1NFileDo");
	else if (ix == DPCHAPPIDECNAVDO) return("DpchAppIdecNavDo");
	else if (ix == DPCHAPPIDECNAVMAINTDATA) return("DpchAppIdecNavMaintData");
	else if (ix == DPCHAPPIDECNAVMAINTDO) return("DpchAppIdecNavMaintDo");
	else if (ix == DPCHAPPIDECNAVOPRDATA) return("DpchAppIdecNavOprData");
	else if (ix == DPCHAPPIDECNAVOPRDO) return("DpchAppIdecNavOprDo");
	else if (ix == DPCHAPPIDECNAVPREDO) return("DpchAppIdecNavPreDo");
	else if (ix == DPCHAPPIDECRESUME) return("DpchAppIdecResume");
	else if (ix == DPCHAPPIDECSCFCONNDATA) return("DpchAppIdecScfConnData");
	else if (ix == DPCHAPPIDECSCFCONNDO) return("DpchAppIdecScfConnDo");
	else if (ix == DPCHAPPIDECSCFDO) return("DpchAppIdecScfDo");
	else if (ix == DPCHAPPIDECSCFLWIRDATA) return("DpchAppIdecScfLwirData");
	else if (ix == DPCHAPPIDECSCFLWIRDO) return("DpchAppIdecScfLwirDo");
	else if (ix == DPCHAPPIDECSCFMECHDATA) return("DpchAppIdecScfMechData");
	else if (ix == DPCHAPPIDECSCFMECHDO) return("DpchAppIdecScfMechDo");
	else if (ix == DPCHAPPIDECSCFOPTICSDATA) return("DpchAppIdecScfOpticsData");
	else if (ix == DPCHAPPIDECSCFOPTICSDO) return("DpchAppIdecScfOpticsDo");
	else if (ix == DPCHAPPIDECSCFQCDDATA) return("DpchAppIdecScfQcdData");
	else if (ix == DPCHAPPIDECSCFQCDDO) return("DpchAppIdecScfQcdDo");
	else if (ix == DPCHAPPIDECSCFRECORDDATA) return("DpchAppIdecScfRecordData");
	else if (ix == DPCHAPPIDECSCFRECORDDO) return("DpchAppIdecScfRecordDo");
	else if (ix == DPCHAPPIDECSCFSTATUSDO) return("DpchAppIdecScfStatusDo");
	else if (ix == DPCHAPPIDECSCFTRIGGERDATA) return("DpchAppIdecScfTriggerData");
	else if (ix == DPCHAPPIDECSCFTRIGGERDO) return("DpchAppIdecScfTriggerDo");
	else if (ix == DPCHAPPIDECTOUDETAILDATA) return("DpchAppIdecTouDetailData");
	else if (ix == DPCHAPPIDECTOUDETAILDO) return("DpchAppIdecTouDetailDo");
	else if (ix == DPCHAPPIDECTOUDO) return("DpchAppIdecTouDo");
	else if (ix == DPCHAPPIDECTOULISTDATA) return("DpchAppIdecTouListData");
	else if (ix == DPCHAPPIDECTOULISTDO) return("DpchAppIdecTouListDo");
	else if (ix == DPCHAPPIDECTOURECDO) return("DpchAppIdecTouRecDo");
	else if (ix == DPCHAPPIDECTOUREF1NFILEDATA) return("DpchAppIdecTouRef1NFileData");
	else if (ix == DPCHAPPIDECTOUREF1NFILEDO) return("DpchAppIdecTouRef1NFileDo");
	else if (ix == DPCHAPPIDECUSGAACCESSDATA) return("DpchAppIdecUsgAAccessData");
	else if (ix == DPCHAPPIDECUSGAACCESSDO) return("DpchAppIdecUsgAAccessDo");
	else if (ix == DPCHAPPIDECUSGDETAILDATA) return("DpchAppIdecUsgDetailData");
	else if (ix == DPCHAPPIDECUSGDETAILDO) return("DpchAppIdecUsgDetailDo");
	else if (ix == DPCHAPPIDECUSGDO) return("DpchAppIdecUsgDo");
	else if (ix == DPCHAPPIDECUSGLISTDATA) return("DpchAppIdecUsgListData");
	else if (ix == DPCHAPPIDECUSGLISTDO) return("DpchAppIdecUsgListDo");
	else if (ix == DPCHAPPIDECUSGMNUSERDATA) return("DpchAppIdecUsgMNUserData");
	else if (ix == DPCHAPPIDECUSGMNUSERDO) return("DpchAppIdecUsgMNUserDo");
	else if (ix == DPCHAPPIDECUSGRECDO) return("DpchAppIdecUsgRecDo");
	else if (ix == DPCHAPPIDECUSR1NSESSIONDATA) return("DpchAppIdecUsr1NSessionData");
	else if (ix == DPCHAPPIDECUSR1NSESSIONDO) return("DpchAppIdecUsr1NSessionDo");
	else if (ix == DPCHAPPIDECUSRAACCESSDATA) return("DpchAppIdecUsrAAccessData");
	else if (ix == DPCHAPPIDECUSRAACCESSDO) return("DpchAppIdecUsrAAccessDo");
	else if (ix == DPCHAPPIDECUSRDETAILDATA) return("DpchAppIdecUsrDetailData");
	else if (ix == DPCHAPPIDECUSRDETAILDO) return("DpchAppIdecUsrDetailDo");
	else if (ix == DPCHAPPIDECUSRDO) return("DpchAppIdecUsrDo");
	else if (ix == DPCHAPPIDECUSRLISTDATA) return("DpchAppIdecUsrListData");
	else if (ix == DPCHAPPIDECUSRLISTDO) return("DpchAppIdecUsrListDo");
	else if (ix == DPCHAPPIDECUSRMNUSERGROUPDATA) return("DpchAppIdecUsrMNUsergroupData");
	else if (ix == DPCHAPPIDECUSRMNUSERGROUPDO) return("DpchAppIdecUsrMNUsergroupDo");
	else if (ix == DPCHAPPIDECUSRRECDO) return("DpchAppIdecUsrRecDo");
	else if (ix == DPCHAPPIDECUTLDO) return("DpchAppIdecUtlDo");
	else if (ix == DPCHAPPIDECUTLSPITERMDATA) return("DpchAppIdecUtlSpitermData");
	else if (ix == DPCHAPPIDECUTLSPITERMDO) return("DpchAppIdecUtlSpitermDo");
	else if (ix == DPCHAPPROOTIDECLOGIN) return("DpchAppRootIdecLogin");
	else if (ix == DPCHENGDLGIDECFILEXTRMEDDATA) return("DpchEngDlgIdecFilExtrmedData");
	else if (ix == DPCHENGDLGIDECMISNEWDATA) return("DpchEngDlgIdecMisNewData");
	else if (ix == DPCHENGDLGIDECNAVLOAINIDATA) return("DpchEngDlgIdecNavLoainiData");
	else if (ix == DPCHENGDLGIDECTOUNEWDATA) return("DpchEngDlgIdecTouNewData");
	else if (ix == DPCHENGDLGIDECUTLFUSIONDATA) return("DpchEngDlgIdecUtlFusionData");
	else if (ix == DPCHENGDLGIDECUTLPHIDATA) return("DpchEngDlgIdecUtlPhiData");
	else if (ix == DPCHENGDLGIDECUTLQCDALNDATA) return("DpchEngDlgIdecUtlQcdalnData");
	else if (ix == DPCHENGDLGIDECUTLQCDNUCDATA) return("DpchEngDlgIdecUtlQcdnucData");
	else if (ix == DPCHENGDLGIDECUTLSTEREODATA) return("DpchEngDlgIdecUtlStereoData");
	else if (ix == DPCHENGDLGIDECUTLTHETADATA) return("DpchEngDlgIdecUtlThetaData");
	else if (ix == DPCHENGIDECACK) return("DpchEngIdecAck");
	else if (ix == DPCHENGIDECAD1CONTROLDATA) return("DpchEngIdecAd1ControlData");
	else if (ix == DPCHENGIDECAD1DATA) return("DpchEngIdecAd1Data");
	else if (ix == DPCHENGIDECAD1HEADBARDATA) return("DpchEngIdecAd1HeadbarData");
	else if (ix == DPCHENGIDECALERT) return("DpchEngIdecAlert");
	else if (ix == DPCHENGIDECCONFIRM) return("DpchEngIdecConfirm");
	else if (ix == DPCHENGIDECFILDATA) return("DpchEngIdecFilData");
	else if (ix == DPCHENGIDECFILDETAILDATA) return("DpchEngIdecFilDetailData");
	else if (ix == DPCHENGIDECFILHEADBARDATA) return("DpchEngIdecFilHeadbarData");
	else if (ix == DPCHENGIDECFILLISTDATA) return("DpchEngIdecFilListData");
	else if (ix == DPCHENGIDECFILRECDATA) return("DpchEngIdecFilRecData");
	else if (ix == DPCHENGIDECIAQDATA) return("DpchEngIdecIaqData");
	else if (ix == DPCHENGIDECIAQHEADBARDATA) return("DpchEngIdecIaqHeadbarData");
	else if (ix == DPCHENGIDECIAQLIVEDATA) return("DpchEngIdecIaqLiveData");
	else if (ix == DPCHENGIDECIAQLIVELIVE) return("DpchEngIdecIaqLiveLive");
	else if (ix == DPCHENGIDECIAQMECHDATA) return("DpchEngIdecIaqMechData");
	else if (ix == DPCHENGIDECIAQMECHLIVE) return("DpchEngIdecIaqMechLive");
	else if (ix == DPCHENGIDECIAQQCDSPDATA) return("DpchEngIdecIaqQcdspData");
	else if (ix == DPCHENGIDECIAQQCDSPLIVE) return("DpchEngIdecIaqQcdspLive");
	else if (ix == DPCHENGIDECIAQSCILLDATA) return("DpchEngIdecIaqScillData");
	else if (ix == DPCHENGIDECMIS1NTOURDATA) return("DpchEngIdecMis1NTourData");
	else if (ix == DPCHENGIDECMISDATA) return("DpchEngIdecMisData");
	else if (ix == DPCHENGIDECMISDETAILDATA) return("DpchEngIdecMisDetailData");
	else if (ix == DPCHENGIDECMISHEADBARDATA) return("DpchEngIdecMisHeadbarData");
	else if (ix == DPCHENGIDECMISLISTDATA) return("DpchEngIdecMisListData");
	else if (ix == DPCHENGIDECMISRECDATA) return("DpchEngIdecMisRecData");
	else if (ix == DPCHENGIDECMISREF1NFILEDATA) return("DpchEngIdecMisRef1NFileData");
	else if (ix == DPCHENGIDECNAVDATA) return("DpchEngIdecNavData");
	else if (ix == DPCHENGIDECNAVHEADBARDATA) return("DpchEngIdecNavHeadbarData");
	else if (ix == DPCHENGIDECNAVMAINTDATA) return("DpchEngIdecNavMaintData");
	else if (ix == DPCHENGIDECNAVOPRDATA) return("DpchEngIdecNavOprData");
	else if (ix == DPCHENGIDECNAVPREDATA) return("DpchEngIdecNavPreData");
	else if (ix == DPCHENGIDECSCFCONNDATA) return("DpchEngIdecScfConnData");
	else if (ix == DPCHENGIDECSCFCONNLIVE) return("DpchEngIdecScfConnLive");
	else if (ix == DPCHENGIDECSCFDATA) return("DpchEngIdecScfData");
	else if (ix == DPCHENGIDECSCFHEADBARDATA) return("DpchEngIdecScfHeadbarData");
	else if (ix == DPCHENGIDECSCFLWIRDATA) return("DpchEngIdecScfLwirData");
	else if (ix == DPCHENGIDECSCFMECHDATA) return("DpchEngIdecScfMechData");
	else if (ix == DPCHENGIDECSCFMECHLIVE) return("DpchEngIdecScfMechLive");
	else if (ix == DPCHENGIDECSCFOPTICSDATA) return("DpchEngIdecScfOpticsData");
	else if (ix == DPCHENGIDECSCFQCDDATA) return("DpchEngIdecScfQcdData");
	else if (ix == DPCHENGIDECSCFRECORDDATA) return("DpchEngIdecScfRecordData");
	else if (ix == DPCHENGIDECSCFSTATUSDATA) return("DpchEngIdecScfStatusData");
	else if (ix == DPCHENGIDECSCFTRIGGERDATA) return("DpchEngIdecScfTriggerData");
	else if (ix == DPCHENGIDECSUSPEND) return("DpchEngIdecSuspend");
	else if (ix == DPCHENGIDECTOUDATA) return("DpchEngIdecTouData");
	else if (ix == DPCHENGIDECTOUDETAILDATA) return("DpchEngIdecTouDetailData");
	else if (ix == DPCHENGIDECTOUHEADBARDATA) return("DpchEngIdecTouHeadbarData");
	else if (ix == DPCHENGIDECTOULISTDATA) return("DpchEngIdecTouListData");
	else if (ix == DPCHENGIDECTOURECDATA) return("DpchEngIdecTouRecData");
	else if (ix == DPCHENGIDECTOUREF1NFILEDATA) return("DpchEngIdecTouRef1NFileData");
	else if (ix == DPCHENGIDECUSGAACCESSDATA) return("DpchEngIdecUsgAAccessData");
	else if (ix == DPCHENGIDECUSGDATA) return("DpchEngIdecUsgData");
	else if (ix == DPCHENGIDECUSGDETAILDATA) return("DpchEngIdecUsgDetailData");
	else if (ix == DPCHENGIDECUSGHEADBARDATA) return("DpchEngIdecUsgHeadbarData");
	else if (ix == DPCHENGIDECUSGLISTDATA) return("DpchEngIdecUsgListData");
	else if (ix == DPCHENGIDECUSGMNUSERDATA) return("DpchEngIdecUsgMNUserData");
	else if (ix == DPCHENGIDECUSGRECDATA) return("DpchEngIdecUsgRecData");
	else if (ix == DPCHENGIDECUSR1NSESSIONDATA) return("DpchEngIdecUsr1NSessionData");
	else if (ix == DPCHENGIDECUSRAACCESSDATA) return("DpchEngIdecUsrAAccessData");
	else if (ix == DPCHENGIDECUSRDATA) return("DpchEngIdecUsrData");
	else if (ix == DPCHENGIDECUSRDETAILDATA) return("DpchEngIdecUsrDetailData");
	else if (ix == DPCHENGIDECUSRHEADBARDATA) return("DpchEngIdecUsrHeadbarData");
	else if (ix == DPCHENGIDECUSRLISTDATA) return("DpchEngIdecUsrListData");
	else if (ix == DPCHENGIDECUSRMNUSERGROUPDATA) return("DpchEngIdecUsrMNUsergroupData");
	else if (ix == DPCHENGIDECUSRRECDATA) return("DpchEngIdecUsrRecData");
	else if (ix == DPCHENGIDECUTLDATA) return("DpchEngIdecUtlData");
	else if (ix == DPCHENGIDECUTLHEADBARDATA) return("DpchEngIdecUtlHeadbarData");
	else if (ix == DPCHENGIDECUTLSPITERMDATA) return("DpchEngIdecUtlSpitermData");
	else if (ix == DPCHENGIDECUTLSPITERMLIVE) return("DpchEngIdecUtlSpitermLive");
	else if (ix == DPCHENGSESSIDECDATA) return("DpchEngSessIdecData");
	else if (ix == DPCHIDECDACK) return("DpchIdecdAck");
	else if (ix == DPCHIDECDQUIT) return("DpchIdecdQuit");
	else if (ix == DPCHIDECDREG) return("DpchIdecdReg");
	else if (ix == DPCHIDECOPDREG) return("DpchIdecopdReg");
	else if (ix == DPCHIDECOPDUNREG) return("DpchIdecopdUnreg");
	else if (ix == DPCHINVIDEC) return("DpchInvIdec");
	else if (ix == DPCHRETIDEC) return("DpchRetIdec");

	return("");
};

