/**
  * \file VecIdecVDpch.h
  * vector VecIdecVDpch (declarations)
  * \author Alexander Wirthmueller
  * \date created: 30 Dec 2017
  * \date modified: 30 Dec 2017
  */

#ifndef VECIDECVDPCH_H
#define VECIDECVDPCH_H

#include <sbecore/Xmlio.h>

using namespace Xmlio;

/**
	* VecIdecVDpch
	*/
namespace VecIdecVDpch {
	const uint DPCHAPPDLGIDECFILEXTRMEDDATA = 1;
	const uint DPCHAPPDLGIDECFILEXTRMEDDO = 2;
	const uint DPCHAPPDLGIDECMISNEWDATA = 3;
	const uint DPCHAPPDLGIDECMISNEWDO = 4;
	const uint DPCHAPPDLGIDECNAVLOAINIDATA = 5;
	const uint DPCHAPPDLGIDECNAVLOAINIDO = 6;
	const uint DPCHAPPDLGIDECTOUNEWDATA = 7;
	const uint DPCHAPPDLGIDECTOUNEWDO = 8;
	const uint DPCHAPPDLGIDECUTLFUSIONDATA = 9;
	const uint DPCHAPPDLGIDECUTLFUSIONDO = 10;
	const uint DPCHAPPDLGIDECUTLPHIDATA = 11;
	const uint DPCHAPPDLGIDECUTLPHIDO = 12;
	const uint DPCHAPPDLGIDECUTLQCDALNDATA = 13;
	const uint DPCHAPPDLGIDECUTLQCDALNDO = 14;
	const uint DPCHAPPDLGIDECUTLQCDNUCDATA = 15;
	const uint DPCHAPPDLGIDECUTLQCDNUCDO = 16;
	const uint DPCHAPPDLGIDECUTLSTEREODATA = 17;
	const uint DPCHAPPDLGIDECUTLSTEREODO = 18;
	const uint DPCHAPPDLGIDECUTLTHETADATA = 19;
	const uint DPCHAPPDLGIDECUTLTHETADO = 20;
	const uint DPCHAPPIDECAD1CONTROLDATA = 21;
	const uint DPCHAPPIDECAD1CONTROLDO = 22;
	const uint DPCHAPPIDECAD1DO = 23;
	const uint DPCHAPPIDECALERT = 24;
	const uint DPCHAPPIDECFILDETAILDATA = 25;
	const uint DPCHAPPIDECFILDETAILDO = 26;
	const uint DPCHAPPIDECFILDO = 27;
	const uint DPCHAPPIDECFILLISTDATA = 28;
	const uint DPCHAPPIDECFILLISTDO = 29;
	const uint DPCHAPPIDECFILRECDO = 30;
	const uint DPCHAPPIDECIAQDO = 31;
	const uint DPCHAPPIDECIAQLIVEDATA = 32;
	const uint DPCHAPPIDECIAQLIVEDO = 33;
	const uint DPCHAPPIDECIAQMECHDATA = 34;
	const uint DPCHAPPIDECIAQMECHDO = 35;
	const uint DPCHAPPIDECIAQQCDSPDATA = 36;
	const uint DPCHAPPIDECIAQQCDSPDO = 37;
	const uint DPCHAPPIDECIAQSCILLDATA = 38;
	const uint DPCHAPPIDECIAQSCILLDO = 39;
	const uint DPCHAPPIDECINIT = 40;
	const uint DPCHAPPIDECMIS1NTOURDATA = 41;
	const uint DPCHAPPIDECMIS1NTOURDO = 42;
	const uint DPCHAPPIDECMISDETAILDATA = 43;
	const uint DPCHAPPIDECMISDETAILDO = 44;
	const uint DPCHAPPIDECMISDO = 45;
	const uint DPCHAPPIDECMISLISTDATA = 46;
	const uint DPCHAPPIDECMISLISTDO = 47;
	const uint DPCHAPPIDECMISRECDO = 48;
	const uint DPCHAPPIDECMISREF1NFILEDATA = 49;
	const uint DPCHAPPIDECMISREF1NFILEDO = 50;
	const uint DPCHAPPIDECNAVDO = 51;
	const uint DPCHAPPIDECNAVMAINTDATA = 52;
	const uint DPCHAPPIDECNAVMAINTDO = 53;
	const uint DPCHAPPIDECNAVOPRDATA = 54;
	const uint DPCHAPPIDECNAVOPRDO = 55;
	const uint DPCHAPPIDECNAVPREDO = 56;
	const uint DPCHAPPIDECRESUME = 57;
	const uint DPCHAPPIDECSCFCONNDATA = 58;
	const uint DPCHAPPIDECSCFCONNDO = 59;
	const uint DPCHAPPIDECSCFDO = 60;
	const uint DPCHAPPIDECSCFLWIRDATA = 61;
	const uint DPCHAPPIDECSCFLWIRDO = 62;
	const uint DPCHAPPIDECSCFMECHDATA = 63;
	const uint DPCHAPPIDECSCFMECHDO = 64;
	const uint DPCHAPPIDECSCFOPTICSDATA = 65;
	const uint DPCHAPPIDECSCFOPTICSDO = 66;
	const uint DPCHAPPIDECSCFQCDDATA = 67;
	const uint DPCHAPPIDECSCFQCDDO = 68;
	const uint DPCHAPPIDECSCFRECORDDATA = 69;
	const uint DPCHAPPIDECSCFRECORDDO = 70;
	const uint DPCHAPPIDECSCFSTATUSDO = 71;
	const uint DPCHAPPIDECSCFTRIGGERDATA = 72;
	const uint DPCHAPPIDECSCFTRIGGERDO = 73;
	const uint DPCHAPPIDECTOUDETAILDATA = 74;
	const uint DPCHAPPIDECTOUDETAILDO = 75;
	const uint DPCHAPPIDECTOUDO = 76;
	const uint DPCHAPPIDECTOULISTDATA = 77;
	const uint DPCHAPPIDECTOULISTDO = 78;
	const uint DPCHAPPIDECTOURECDO = 79;
	const uint DPCHAPPIDECTOUREF1NFILEDATA = 80;
	const uint DPCHAPPIDECTOUREF1NFILEDO = 81;
	const uint DPCHAPPIDECUSGAACCESSDATA = 82;
	const uint DPCHAPPIDECUSGAACCESSDO = 83;
	const uint DPCHAPPIDECUSGDETAILDATA = 84;
	const uint DPCHAPPIDECUSGDETAILDO = 85;
	const uint DPCHAPPIDECUSGDO = 86;
	const uint DPCHAPPIDECUSGLISTDATA = 87;
	const uint DPCHAPPIDECUSGLISTDO = 88;
	const uint DPCHAPPIDECUSGMNUSERDATA = 89;
	const uint DPCHAPPIDECUSGMNUSERDO = 90;
	const uint DPCHAPPIDECUSGRECDO = 91;
	const uint DPCHAPPIDECUSR1NSESSIONDATA = 92;
	const uint DPCHAPPIDECUSR1NSESSIONDO = 93;
	const uint DPCHAPPIDECUSRAACCESSDATA = 94;
	const uint DPCHAPPIDECUSRAACCESSDO = 95;
	const uint DPCHAPPIDECUSRDETAILDATA = 96;
	const uint DPCHAPPIDECUSRDETAILDO = 97;
	const uint DPCHAPPIDECUSRDO = 98;
	const uint DPCHAPPIDECUSRLISTDATA = 99;
	const uint DPCHAPPIDECUSRLISTDO = 100;
	const uint DPCHAPPIDECUSRMNUSERGROUPDATA = 101;
	const uint DPCHAPPIDECUSRMNUSERGROUPDO = 102;
	const uint DPCHAPPIDECUSRRECDO = 103;
	const uint DPCHAPPIDECUTLDO = 104;
	const uint DPCHAPPIDECUTLSPITERMDATA = 105;
	const uint DPCHAPPIDECUTLSPITERMDO = 106;
	const uint DPCHAPPROOTIDECLOGIN = 107;
	const uint DPCHENGDLGIDECFILEXTRMEDDATA = 108;
	const uint DPCHENGDLGIDECMISNEWDATA = 109;
	const uint DPCHENGDLGIDECNAVLOAINIDATA = 110;
	const uint DPCHENGDLGIDECTOUNEWDATA = 111;
	const uint DPCHENGDLGIDECUTLFUSIONDATA = 112;
	const uint DPCHENGDLGIDECUTLPHIDATA = 113;
	const uint DPCHENGDLGIDECUTLQCDALNDATA = 114;
	const uint DPCHENGDLGIDECUTLQCDNUCDATA = 115;
	const uint DPCHENGDLGIDECUTLSTEREODATA = 116;
	const uint DPCHENGDLGIDECUTLTHETADATA = 117;
	const uint DPCHENGIDECACK = 118;
	const uint DPCHENGIDECAD1CONTROLDATA = 119;
	const uint DPCHENGIDECAD1DATA = 120;
	const uint DPCHENGIDECAD1HEADBARDATA = 121;
	const uint DPCHENGIDECALERT = 122;
	const uint DPCHENGIDECCONFIRM = 123;
	const uint DPCHENGIDECFILDATA = 124;
	const uint DPCHENGIDECFILDETAILDATA = 125;
	const uint DPCHENGIDECFILHEADBARDATA = 126;
	const uint DPCHENGIDECFILLISTDATA = 127;
	const uint DPCHENGIDECFILRECDATA = 128;
	const uint DPCHENGIDECIAQDATA = 129;
	const uint DPCHENGIDECIAQHEADBARDATA = 130;
	const uint DPCHENGIDECIAQLIVEDATA = 131;
	const uint DPCHENGIDECIAQLIVELIVE = 132;
	const uint DPCHENGIDECIAQMECHDATA = 133;
	const uint DPCHENGIDECIAQMECHLIVE = 134;
	const uint DPCHENGIDECIAQQCDSPDATA = 135;
	const uint DPCHENGIDECIAQQCDSPLIVE = 136;
	const uint DPCHENGIDECIAQSCILLDATA = 137;
	const uint DPCHENGIDECMIS1NTOURDATA = 138;
	const uint DPCHENGIDECMISDATA = 139;
	const uint DPCHENGIDECMISDETAILDATA = 140;
	const uint DPCHENGIDECMISHEADBARDATA = 141;
	const uint DPCHENGIDECMISLISTDATA = 142;
	const uint DPCHENGIDECMISRECDATA = 143;
	const uint DPCHENGIDECMISREF1NFILEDATA = 144;
	const uint DPCHENGIDECNAVDATA = 145;
	const uint DPCHENGIDECNAVHEADBARDATA = 146;
	const uint DPCHENGIDECNAVMAINTDATA = 147;
	const uint DPCHENGIDECNAVOPRDATA = 148;
	const uint DPCHENGIDECNAVPREDATA = 149;
	const uint DPCHENGIDECSCFCONNDATA = 150;
	const uint DPCHENGIDECSCFCONNLIVE = 151;
	const uint DPCHENGIDECSCFDATA = 152;
	const uint DPCHENGIDECSCFHEADBARDATA = 153;
	const uint DPCHENGIDECSCFLWIRDATA = 154;
	const uint DPCHENGIDECSCFMECHDATA = 155;
	const uint DPCHENGIDECSCFMECHLIVE = 156;
	const uint DPCHENGIDECSCFOPTICSDATA = 157;
	const uint DPCHENGIDECSCFQCDDATA = 158;
	const uint DPCHENGIDECSCFRECORDDATA = 159;
	const uint DPCHENGIDECSCFSTATUSDATA = 160;
	const uint DPCHENGIDECSCFTRIGGERDATA = 161;
	const uint DPCHENGIDECSUSPEND = 162;
	const uint DPCHENGIDECTOUDATA = 163;
	const uint DPCHENGIDECTOUDETAILDATA = 164;
	const uint DPCHENGIDECTOUHEADBARDATA = 165;
	const uint DPCHENGIDECTOULISTDATA = 166;
	const uint DPCHENGIDECTOURECDATA = 167;
	const uint DPCHENGIDECTOUREF1NFILEDATA = 168;
	const uint DPCHENGIDECUSGAACCESSDATA = 169;
	const uint DPCHENGIDECUSGDATA = 170;
	const uint DPCHENGIDECUSGDETAILDATA = 171;
	const uint DPCHENGIDECUSGHEADBARDATA = 172;
	const uint DPCHENGIDECUSGLISTDATA = 173;
	const uint DPCHENGIDECUSGMNUSERDATA = 174;
	const uint DPCHENGIDECUSGRECDATA = 175;
	const uint DPCHENGIDECUSR1NSESSIONDATA = 176;
	const uint DPCHENGIDECUSRAACCESSDATA = 177;
	const uint DPCHENGIDECUSRDATA = 178;
	const uint DPCHENGIDECUSRDETAILDATA = 179;
	const uint DPCHENGIDECUSRHEADBARDATA = 180;
	const uint DPCHENGIDECUSRLISTDATA = 181;
	const uint DPCHENGIDECUSRMNUSERGROUPDATA = 182;
	const uint DPCHENGIDECUSRRECDATA = 183;
	const uint DPCHENGIDECUTLDATA = 184;
	const uint DPCHENGIDECUTLHEADBARDATA = 185;
	const uint DPCHENGIDECUTLSPITERMDATA = 186;
	const uint DPCHENGIDECUTLSPITERMLIVE = 187;
	const uint DPCHENGSESSIDECDATA = 188;
	const uint DPCHIDECDACK = 189;
	const uint DPCHIDECDQUIT = 190;
	const uint DPCHIDECDREG = 191;
	const uint DPCHIDECOPDREG = 192;
	const uint DPCHIDECOPDUNREG = 193;
	const uint DPCHINVIDEC = 194;
	const uint DPCHRETIDEC = 195;

	uint getIx(const string& sref);
	string getSref(const uint ix);
};

#endif

