# file Makefile.inc
# make file paths for Idec daemon, release idecd_ungenio
# author Alexander Wirthmueller
# date created: 30 Dec 2017
# modified: 30 Dec 2017

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin

