# file Makefile.inc
# make file paths for Idec combined daemon, release ideccmbd_che
# author Alexander Wirthmueller
# date created: 30 Dec 2017
# modified: 30 Dec 2017

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin

